version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - export COMMIT_HASH_SHORT="$(echo $COMMIT_HASH | cut -c 1-7)"
  build:
    commands:
      - echo Building the Docker image...
      - docker build --tag ${REPOSITORY_URI}:${COMMIT_HASH_SHORT} --tag ${REPOSITORY_URI}:${BRANCH_NAME} .
      # This config tests the codebuild login and the build but does not push dev images.
      # The following line can be temporarily uncommented to test a dev image.
      # - docker image push --all-tags  ${REPOSITORY_URI}
  post_build:
    commands:
      - echo AWS CodeBuild Process has terminated.
      - printf '{"tag":"%s"}' $COMMIT_HASH_SHORT > build.json